package ui;

import control.DeliveryManControl;
import domain.DeliveryManDomain;
import da.DeliveryManDA;
import javax.swing.*;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
/**
 *
 * @author annoy
 */
class JTextFieldLimit extends PlainDocument {
  private int limit;
  JTextFieldLimit(int limit) {
    super();
    this.limit = limit;
  }

  JTextFieldLimit(int limit, boolean upper) {
    super();
    this.limit = limit;
  }

  public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
    if (str == null)
      return;

    if ((getLength() + str.length()) <= limit) {
      super.insertString(offset, str, attr);
    }
  }
}
public class DeliveryManManagement extends javax.swing.JFrame {
 
    private DeliveryManControl Deliverycontrol;
    private DeliveryManDA DMDA = new DeliveryManDA();
    public DeliveryManManagement() {
        Deliverycontrol = new DeliveryManControl();
        initComponents();
        setTitle("Delivery Man Management");
        jtfDeliveryArea.setDocument(new JTextFieldLimit(30));
        jtfName.setDocument(new JTextFieldLimit(30));
        jtfIC.setDocument(new JTextFieldLimit(14));
        jtfAge.setDocument(new JTextFieldLimit(3));
        jtfGender.setDocument(new JTextFieldLimit(1));
        jtfPhone.setDocument(new JTextFieldLimit(11));
        jtfEmail.setDocument(new JTextFieldLimit(30));
        jtfAccPw.setDocument(new JTextFieldLimit(29));
        jtfAddress.setDocument(new JTextFieldLimit(50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfDeliveryArea = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfIC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfAge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfGender = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfAccPw = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jtfName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfAddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Delivery Man Management");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, null, null));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Name:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(12, 13, 40, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Delivery Area:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 40, 85, 17);

        jtfDeliveryArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDeliveryAreaActionPerformed(evt);
            }
        });
        jPanel2.add(jtfDeliveryArea);
        jtfDeliveryArea.setBounds(120, 40, 220, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("IC:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 70, 18, 17);
        jPanel2.add(jtfIC);
        jtfIC.setBounds(120, 70, 220, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Age:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 100, 28, 17);
        jPanel2.add(jtfAge);
        jtfAge.setBounds(120, 100, 220, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Gender:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 130, 49, 17);
        jPanel2.add(jtfGender);
        jtfGender.setBounds(120, 130, 220, 25);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Phone:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 160, 44, 17);
        jPanel2.add(jtfPhone);
        jtfPhone.setBounds(120, 160, 220, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Email:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 190, 36, 17);
        jPanel2.add(jtfAccPw);
        jtfAccPw.setBounds(120, 220, 220, 25);

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setAutoscrolls(true);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);
        btnAdd.setBounds(50, 310, 80, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Acc Password:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 220, 100, 20);
        jPanel2.add(jtfEmail);
        jtfEmail.setBounds(120, 190, 220, 25);

        jtfName.setMaximumSize(new java.awt.Dimension(6, 18));
        jtfName.setMinimumSize(new java.awt.Dimension(6, 18));
        jtfName.setName(""); // NOI18N
        jtfName.setPreferredSize(new java.awt.Dimension(6, 18));
        jtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNameActionPerformed(evt);
            }
        });
        jPanel2.add(jtfName);
        jtfName.setBounds(120, 10, 220, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Address:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 250, 90, 20);
        jPanel2.add(jtfAddress);
        jtfAddress.setBounds(120, 250, 220, 25);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDeliveryAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDeliveryAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDeliveryAreaActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        String chkgen = jtfGender.getText();
        String chkjob = jtfDeliveryArea.getText();
        String chkIC = jtfIC.getText();
        String chkphn = jtfPhone.getText();
        String Staffphn = jtfPhone.getText();
        
        String DManid = DMDA.generateStaffID();

        
            if(chkIC.charAt(6) == '-' && chkIC.charAt(9) == '-'){
                if(chkgen.charAt(0) == 'F' || chkgen.charAt(0) == 'M'){
                    if(chkphn.substring(0,2).equals("01")){
                    if(chkphn.indexOf('-')==3){
                        
                            DeliveryManDomain s = new DeliveryManDomain(DManid, jtfName.getText() , jtfDeliveryArea.getText(), jtfIC.getText(), jtfAge.getText(), jtfGender.getText(), jtfPhone.getText(), jtfEmail.getText(), jtfAccPw.getText(), jtfAddress.getText());
                            Deliverycontrol.AddStaff(s);
                            JOptionPane.showMessageDialog(null, "New Staff added, your staff id is " + DManid);
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "Wrong phone number format, please make sure it is 01X-xxxxxxxx", "FORMAT ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Wrong phone number format, please make sure it is 01X-xxxxxxxx", "FORMAT ERROR", JOptionPane.ERROR_MESSAGE);
                }
                }else{
                    JOptionPane.showMessageDialog(null, "Wrong Gender format, please enter M for male and F for female and make sure it is capital letter", "FORMAT ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Wrong IC format, please make sure the format is XXXXXX-XX-XXXX", "FORMAT ERROR", JOptionPane.ERROR_MESSAGE);
            
            }

    }//GEN-LAST:event_btnAddActionPerformed

    private void jtfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryManManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryManManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryManManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryManManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryManManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtfAccPw;
    private javax.swing.JTextField jtfAddress;
    private javax.swing.JTextField jtfAge;
    private javax.swing.JTextField jtfDeliveryArea;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfGender;
    private javax.swing.JTextField jtfIC;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPhone;
    // End of variables declaration//GEN-END:variables
}
